{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "felix.fullname" . }}
  labels:
    {{- include "felix.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name | quote }}
    kind: {{ .Values.externalSecrets.secretStore.kind | quote }}
  target:
    name: {{ default (include "felix.fullname" .) .Values.externalSecrets.targetSecretName | quote }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        {{- if .property }}
        property: {{ .property | quote }}
        {{- end }}
    {{- end }}
{{- end }}
