"""A2A agent card builder."""

from __future__ import annotations

from typing import Any

from felix.manifests.schema import Manifest


def build_agent_card(
    manifest: Manifest,
    *,
    base_url: str = "",
    mcp_enabled: bool = True,
) -> dict[str, Any]:
    name = manifest.metadata.name
    description = manifest.metadata.description or f"Felix agent {name}"
    if manifest.spec.governance.transparency_notice:
        notice = (
            f"You are interacting with an AI agent ({name}). Responses are generated by automated systems."
        )
        description = f"{description} — {notice}" if description else notice
    a2a = manifest.spec.a2a
    capabilities: dict[str, Any] = {
        "streaming": True,
        "mcp": mcp_enabled,
    }
    # `spec.a2a.capabilities` was declared and never read, so the card advertised the
    # same two transport capabilities for every agent regardless of what it declared.
    for cap in a2a.capabilities or []:
        entry: dict[str, Any] = {"id": cap.id}
        if cap.description:
            entry["description"] = cap.description
        if cap.input_schema_ref:
            entry["inputSchemaRef"] = cap.input_schema_ref
        capabilities.setdefault("declared", []).append(entry)

    card: dict[str, Any] = {
        "name": name,
        "description": description,
        "url": f"{base_url.rstrip('/')}/chat" if base_url else "",
        "version": manifest.metadata.version,
        "capabilities": capabilities,
        # `spec.skills` was never surfaced, so the card claimed the agent had none.
        "skills": [
            {
                "id": s.name,
                "name": s.name,
                **({"description": s.description} if s.description else {}),
                **({"version": s.version} if s.version else {}),
            }
            for s in (manifest.spec.skills or [])
        ],
        "transparencyNotice": bool(manifest.spec.governance.transparency_notice),
    }
    return card


def is_published(manifest: Manifest) -> bool:
    """Whether this agent consents to being advertised over A2A discovery.

    `spec.a2a.publish` defaults to false and was never read, so every agent was
    advertised — including ones an operator had explicitly not published.
    """
    return bool(manifest.spec.a2a.publish)
