#!/usr/bin/env bash
# Ensure .env has a local API key so `make up` starts authenticated.
#
# The container binds 0.0.0.0 and Compose publishes the port, so FELIX_AUTH_MODE=none
# would expose PUT /manifests — and therefore stdio MCP command execution — to anything
# that can route to the host. Rather than make the operator hand-roll a key before the
# first run, generate one and print it.
#
# Idempotent: an existing FELIX_AUTH_API_KEYS is never overwritten.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: no .env — run 'cp .env.example .env' and set POSTGRES_PASSWORD first." >&2
  exit 1
fi

if grep -qE '^[[:space:]]*FELIX_AUTH_API_KEYS=.+' "$ENV_FILE"; then
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  token="sk-felix-local-$(openssl rand -hex 24)"
else
  token="sk-felix-local-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

# Full scopes: this is a local operator key, equivalent to the previous no-auth default.
printf '\n# Generated by scripts/dev-key.sh on first `make up`. Local development only.\n' >> "$ENV_FILE"
printf 'FELIX_AUTH_MODE=api_key\n' >> "$ENV_FILE"
printf 'FELIX_AUTH_API_KEYS={"%s":{"tenant_id":"default","sub":"local-dev","scopes":["admin"]}}\n' \
  "$token" >> "$ENV_FILE"

cat >&2 <<MSG

  Generated a local API key and wrote it to .env:

    $token

  Use it on every request:
    curl -H 'authorization: Bearer $token' http://localhost:8080/health

  Delete the FELIX_AUTH_API_KEYS line to regenerate. Do not use this key off-host.

MSG
