#!/usr/bin/env python3
"""Write, or check, the wire contract: the OpenAPI document and the SSE event vocabulary.

Two checked-in snapshots, `schemas/openapi.json` and `schemas/sse-events.json`, so a change to
either surface shows up as a diff a reviewer reads rather than as a client that silently stops
understanding the server. felix-run/web mirrors the stream's event names by hand, with an open arm
in its union: an added or renamed frame did nothing on either side and nothing said so.

    uv run python scripts/gen-wire-contract.py            # regenerate both
    uv run python scripts/gen-wire-contract.py --check    # fail if either is stale (CI)

The event names are read off the source, not a registry, because there is no registry: a frame's
name is whatever string reaches `Event(event=...)`, a `{"event": ..., "data": ...}` frame, or
`side_events.emit(thread, <name>, ...)`. A site whose name is not a literal has to be one of the
pass-throughs in `PASS_THROUGH` — code that forwards a name it was handed — or the scan fails, so
a new dynamic producer cannot add names the snapshot never sees.
"""

from __future__ import annotations

import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOTS = [
    ROOT / "packages" / "harness" / "src",
    ROOT / "apps" / "api" / "src",
    ROOT / "packages" / "ai" / "src",
]
OPENAPI = ROOT / "schemas" / "openapi.json"
SSE_EVENTS = ROOT / "schemas" / "sse-events.json"

# (file, expression) → why it forwards a name rather than choosing one.
PASS_THROUGH = {
    (
        "packages/harness/src/felix/side_events.py",
        "event",
    ): "the side-event plumbing; its callers name the event",
    ("packages/harness/src/felix/patterns/react.py", "str(side['event'])"): "re-emits a drained side event",
    ("packages/harness/src/felix/patterns/types.py", "self.event"): "an Event serialising itself",
    ("packages/harness/src/felix/governance/reply.py", "item.event"): "re-emits a held frame, screened",
}
# The one frame spelled with `event:` rather than inside `data:` (see `routes/_sse.py`).
ERROR_EVENT = "error"


def _is_event_call(node: ast.Call) -> bool:
    name = getattr(node.func, "id", None) or getattr(node.func, "attr", None)
    return name == "Event" and bool(node.args or node.keywords)


def _is_side_emit(node: ast.Call) -> bool:
    name = getattr(node.func, "id", None) or getattr(node.func, "attr", None)
    return name in {"emit_side_event", "emit"} and len(node.args) >= 2


def scan() -> tuple[set[str], list[str]]:
    """`(event names, unexplained dynamic sites)`."""
    names: set[str] = set()
    unexplained: list[str] = []

    def take(path: Path, value: ast.expr | None) -> None:
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            names.add(value.value)
            return
        rel = str(path.relative_to(ROOT))
        expr = ast.unparse(value) if value is not None else "None"
        if (rel, expr) not in PASS_THROUGH:
            unexplained.append(f"{rel}: {expr}")

    for root in SOURCE_ROOTS:
        for path in sorted(root.rglob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            side_module = path.name == "side_events.py" or any(
                isinstance(n, ast.ImportFrom) and n.module == "felix.side_events" for n in ast.walk(tree)
            )
            for node in ast.walk(tree):
                if isinstance(node, ast.Call) and _is_event_call(node):
                    kw = next((k.value for k in node.keywords if k.arg == "event"), None)
                    take(path, kw if kw is not None else node.args[0])
                elif isinstance(node, ast.Call) and side_module and _is_side_emit(node):
                    take(path, node.args[1])
                elif isinstance(node, ast.Dict):
                    keys = {
                        k.value: v
                        for k, v in zip(node.keys, node.values, strict=True)
                        if isinstance(k, ast.Constant)
                    }
                    if "event" in keys and "data" in keys:
                        take(path, keys["event"])
    return names, unexplained


def build_events() -> dict:
    names, unexplained = scan()
    if unexplained:
        raise SystemExit(
            "event names this scan cannot read — make the name a literal, or add the site to "
            "PASS_THROUGH with the reason it forwards a name:\n  " + "\n  ".join(unexplained)
        )
    return {
        "note": "Generated by scripts/gen-wire-contract.py — every SSE frame name the server can emit.",
        "events": sorted(names),
        "error_event": ERROR_EVENT,
    }


def build_openapi() -> dict:
    sys.path.insert(0, str(ROOT / "scripts"))
    from importlib import import_module

    spec = import_module("export-openapi").build_spec()
    # The release's own export carries the version; the snapshot is for reviewing the surface,
    # and a version in it would go stale on every bump with nothing about the API changed.
    spec.get("info", {}).pop("version", None)
    return spec


def _dump(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    wanted = {OPENAPI: _dump(build_openapi()), SSE_EVENTS: _dump(build_events())}
    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if check:
        if stale:
            names = ", ".join(str(p.relative_to(ROOT)) for p in stale)
            print(f"stale wire contract: {names} — run `make contract` and review the diff", file=sys.stderr)
            return 1
        print("wire contract is current")
        return 0
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {', '.join(str(p.relative_to(ROOT)) for p in wanted)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
