#!/usr/bin/env bash
# Mint a zero-scope API key so Prometheus can scrape the API's /metrics.
#
# /metrics is deliberately not public: its label values include tenant-supplied manifest
# ids and remote MCP tool names, so an anonymous scrape discloses every tenant's manifests
# and tools. Compose defaults to FELIX_AUTH_MODE=api_key, so the scraper needs a credential.
#
# It gets its own key rather than reusing the operator key from scripts/dev-key.sh, with
# an empty `scopes` array. /metrics has no scope gate — any valid key is accepted — so the
# result is a credential that can read metrics and do nothing else. Losing it off-host
# leaks metrics, not write access to PUT /manifests.
#
# Idempotent: an existing FELIX_METRICS_SCRAPE_TOKEN is never regenerated.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"
TOKEN_FILE="deploy/docker/.metrics-token"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: no .env — run 'cp .env.example .env' and set POSTGRES_PASSWORD first." >&2
  exit 1
fi

if ! grep -qE '^[[:space:]]*FELIX_AUTH_API_KEYS=.+' "$ENV_FILE"; then
  echo "error: no FELIX_AUTH_API_KEYS in .env — run 'make up' (or scripts/dev-key.sh) first." >&2
  exit 1
fi

token="$(grep -E '^[[:space:]]*FELIX_METRICS_SCRAPE_TOKEN=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"

if [ -z "$token" ]; then
  if command -v openssl >/dev/null 2>&1; then
    token="sk-felix-scrape-$(openssl rand -hex 24)"
  else
    token="sk-felix-scrape-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi

  # Merge into the existing JSON rather than replacing it — the operator key must survive.
  # python3 because the value is JSON and sed would be guessing at it.
  FELIX_NEW_TOKEN="$token" python3 - "$ENV_FILE" <<'PY'
import json, os, re, sys

path = sys.argv[1]
token = os.environ["FELIX_NEW_TOKEN"]
lines = open(path).read().splitlines(keepends=True)

for i, line in enumerate(lines):
    m = re.match(r"^(\s*FELIX_AUTH_API_KEYS=)(.*)$", line)
    if not m:
        continue
    try:
        keys = json.loads(m.group(2))
    except json.JSONDecodeError:
        sys.exit("FELIX_AUTH_API_KEYS in .env is not valid JSON; fix it by hand")
    if not isinstance(keys, dict):
        sys.exit("FELIX_AUTH_API_KEYS in .env is not a JSON object")
    # No scopes: /metrics needs a valid key, not a privileged one.
    keys[token] = {"tenant_id": "default", "sub": "metrics-scrape", "scopes": []}
    lines[i] = m.group(1) + json.dumps(keys, separators=(",", ":")) + "\n"
    break
else:
    sys.exit("no FELIX_AUTH_API_KEYS line to merge into")

lines.append(f"\n# Generated by scripts/metrics-token.sh for the Prometheus scrape (no scopes).\nFELIX_METRICS_SCRAPE_TOKEN={token}\n")
open(path, "w").write("".join(lines))
PY
fi

# Prometheus reads the bare token from a file; it has no env expansion in scrape configs.
umask 077
printf '%s' "$token" > "$TOKEN_FILE"
chmod 600 "$TOKEN_FILE"
