#!/usr/bin/env bash
# Ensure .env has FELIX_SHELL_RUNNER_TOKEN, the bearer the builder stack's api/worker present to
# its `shell` service (deploy/docker/compose.self.yml). Compose refuses to start that overlay
# without one, rather than run an exec endpoint any container on its network could call.
#
# Idempotent: an existing non-empty value is never overwritten. An empty assignment — the
# placeholder .env.example ships — is replaced in place rather than shadowed by a second line.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: no .env — run 'cp .env.example .env' and set POSTGRES_PASSWORD first." >&2
  exit 1
fi

if grep -qE '^[[:space:]]*FELIX_SHELL_RUNNER_TOKEN=.+' "$ENV_FILE"; then
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  token="$(openssl rand -hex 32)"
else
  token="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

if grep -qE '^[[:space:]]*FELIX_SHELL_RUNNER_TOKEN=$' "$ENV_FILE"; then
  tmp="$(mktemp)"
  sed -E "s|^[[:space:]]*FELIX_SHELL_RUNNER_TOKEN=\$|FELIX_SHELL_RUNNER_TOKEN=${token}|" "$ENV_FILE" > "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
else
  printf '\n# Generated by scripts/shell-runner-token.sh for the builder stack (make up-self).\n' >> "$ENV_FILE"
  printf 'FELIX_SHELL_RUNNER_TOKEN=%s\n' "$token" >> "$ENV_FILE"
fi

echo "Generated FELIX_SHELL_RUNNER_TOKEN into .env for the builder stack's shell runner." >&2
